#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: mysql
#    show-sql: true
#  datasource:
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:rlaqjawls1!}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:test}?characterEncoding=UTF-8&serverTimezone=UTC
#  jackson:
#    property-naming-strategy: SNAKE_CASE